--
-- PostgreSQL database dump
--

\restrict 2SBFzRdgNdXLMOeS3Dh1PHPQoRDODZxBtHPTgoG4nfpBJU1KsCV80xHiErrREbd

-- Dumped from database version 14.20 (Ubuntu 14.20-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.20 (Ubuntu 14.20-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO "FECGLahrMitglieder_user";

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO "FECGLahrMitglieder_user";

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO "FECGLahrMitglieder_user";

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO "FECGLahrMitglieder_user";

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO "FECGLahrMitglieder_user";

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO "FECGLahrMitglieder_user";

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO "FECGLahrMitglieder_user";

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO "FECGLahrMitglieder_user";

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO "FECGLahrMitglieder_user";

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO "FECGLahrMitglieder_user";

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO "FECGLahrMitglieder_user";

--
-- Name: kalender_gemeindetermin; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.kalender_gemeindetermin (
    id bigint NOT NULL,
    titel character varying(200) NOT NULL,
    datum date NOT NULL,
    startzeit time without time zone NOT NULL,
    endzeit time without time zone NOT NULL,
    beschreibung text NOT NULL,
    erstellt_am timestamp with time zone NOT NULL,
    aktualisiert_am timestamp with time zone NOT NULL,
    erstellt_von_id integer
);


ALTER TABLE public.kalender_gemeindetermin OWNER TO "FECGLahrMitglieder_user";

--
-- Name: kalender_gemeindetermin_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.kalender_gemeindetermin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kalender_gemeindetermin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kalender_mitarbeitereintrag; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.kalender_mitarbeitereintrag (
    id bigint NOT NULL,
    person character varying(200) NOT NULL,
    datum date NOT NULL,
    startzeit time without time zone NOT NULL,
    endzeit time without time zone NOT NULL,
    typ character varying(20) NOT NULL,
    titel character varying(200) NOT NULL,
    beschreibung text NOT NULL,
    erstellt_am timestamp with time zone NOT NULL,
    aktualisiert_am timestamp with time zone NOT NULL,
    erstellt_von_id integer
);


ALTER TABLE public.kalender_mitarbeitereintrag OWNER TO "FECGLahrMitglieder_user";

--
-- Name: kalender_mitarbeitereintrag_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.kalender_mitarbeitereintrag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kalender_mitarbeitereintrag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kalender_raumbelegung; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.kalender_raumbelegung (
    id bigint NOT NULL,
    raum character varying(100) NOT NULL,
    titel character varying(200) NOT NULL,
    datum date NOT NULL,
    startzeit time without time zone NOT NULL,
    endzeit time without time zone NOT NULL,
    beschreibung text NOT NULL,
    erstellt_am timestamp with time zone NOT NULL,
    aktualisiert_am timestamp with time zone NOT NULL,
    erstellt_von_id integer
);


ALTER TABLE public.kalender_raumbelegung OWNER TO "FECGLahrMitglieder_user";

--
-- Name: kalender_raumbelegung_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.kalender_raumbelegung ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kalender_raumbelegung_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_familie; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.members_familie (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    family_code character varying(20),
    mutter_id bigint,
    vater_id bigint
);


ALTER TABLE public.members_familie OWNER TO "FECGLahrMitglieder_user";

--
-- Name: members_familie_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.members_familie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_familie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_familie_kinder; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.members_familie_kinder (
    id bigint NOT NULL,
    familie_id bigint NOT NULL,
    member_id bigint NOT NULL
);


ALTER TABLE public.members_familie_kinder OWNER TO "FECGLahrMitglieder_user";

--
-- Name: members_familie_kinder_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.members_familie_kinder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_familie_kinder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_feedback; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.members_feedback (
    id bigint NOT NULL,
    category character varying(50) NOT NULL,
    text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    member_id bigint NOT NULL
);


ALTER TABLE public.members_feedback OWNER TO "FECGLahrMitglieder_user";

--
-- Name: members_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.members_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_gruppe; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.members_gruppe (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    size_type character varying(10) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    parent_gruppe_id bigint
);


ALTER TABLE public.members_gruppe OWNER TO "FECGLahrMitglieder_user";

--
-- Name: members_gruppe_ansprechpartner; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.members_gruppe_ansprechpartner (
    id bigint NOT NULL,
    gruppe_id bigint NOT NULL,
    member_id bigint NOT NULL
);


ALTER TABLE public.members_gruppe_ansprechpartner OWNER TO "FECGLahrMitglieder_user";

--
-- Name: members_gruppe_ansprechpartner_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.members_gruppe_ansprechpartner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_gruppe_ansprechpartner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_gruppe_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.members_gruppe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_gruppe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_gruppe_members; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.members_gruppe_members (
    id bigint NOT NULL,
    gruppe_id bigint NOT NULL,
    member_id bigint NOT NULL
);


ALTER TABLE public.members_gruppe_members OWNER TO "FECGLahrMitglieder_user";

--
-- Name: members_gruppe_members_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.members_gruppe_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_gruppe_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_member; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.members_member (
    id bigint NOT NULL,
    last_name character varying(100) NOT NULL,
    first_name character varying(100) NOT NULL,
    email character varying(254),
    phone character varying(20) NOT NULL,
    street character varying(200) NOT NULL,
    postal_code character varying(10) NOT NULL,
    city character varying(100) NOT NULL,
    date_of_birth date,
    married_since date,
    profession character varying(200) NOT NULL,
    nationality character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    is_donor boolean NOT NULL,
    is_member boolean NOT NULL,
    is_youth boolean NOT NULL,
    is_child boolean NOT NULL,
    community_suggestions text NOT NULL,
    photo character varying(100),
    photo_thumb character varying(100),
    signature character varying(100),
    signature_location character varying(100) NOT NULL,
    privacy_policy_pdf character varying(100),
    privacy_membership boolean NOT NULL,
    privacy_whatsapp boolean NOT NULL,
    privacy_data_protection boolean NOT NULL,
    privacy_data_release boolean NOT NULL,
    privacy_donation boolean NOT NULL,
    privacy_children boolean NOT NULL,
    deleted_at timestamp with time zone,
    anonymized_at timestamp with time zone,
    archived_at timestamp with time zone,
    archival_reason character varying(500) NOT NULL,
    deletion_certificate_url character varying(100),
    deleted_by_id integer,
    marriage_location character varying(100)
);


ALTER TABLE public.members_member OWNER TO "FECGLahrMitglieder_user";

--
-- Name: members_member_current_services; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.members_member_current_services (
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    servicetag_id bigint NOT NULL
);


ALTER TABLE public.members_member_current_services OWNER TO "FECGLahrMitglieder_user";

--
-- Name: members_member_current_services_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.members_member_current_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_member_current_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_member_desired_services; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.members_member_desired_services (
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    servicetag_id bigint NOT NULL
);


ALTER TABLE public.members_member_desired_services OWNER TO "FECGLahrMitglieder_user";

--
-- Name: members_member_desired_services_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.members_member_desired_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_member_desired_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_member_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.members_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members_servicetag; Type: TABLE; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE TABLE public.members_servicetag (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    slug character varying(50) NOT NULL
);


ALTER TABLE public.members_servicetag OWNER TO "FECGLahrMitglieder_user";

--
-- Name: members_servicetag_id_seq; Type: SEQUENCE; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE public.members_servicetag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_servicetag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Token	7	add_token
26	Can change Token	7	change_token
27	Can delete Token	7	delete_token
28	Can view Token	7	view_token
29	Can add Token	8	add_tokenproxy
30	Can change Token	8	change_tokenproxy
31	Can delete Token	8	delete_tokenproxy
32	Can view Token	8	view_tokenproxy
33	Can add Dienst (Tag)	9	add_servicetag
34	Can change Dienst (Tag)	9	change_servicetag
35	Can delete Dienst (Tag)	9	delete_servicetag
36	Can view Dienst (Tag)	9	view_servicetag
37	Can add Mitglied	10	add_member
38	Can change Mitglied	10	change_member
39	Can delete Mitglied	10	delete_member
40	Can view Mitglied	10	view_member
41	Can add Familie	11	add_familie
42	Can change Familie	11	change_familie
43	Can delete Familie	11	delete_familie
44	Can view Familie	11	view_familie
45	Can add Gruppe	12	add_gruppe
46	Can change Gruppe	12	change_gruppe
47	Can delete Gruppe	12	delete_gruppe
48	Can view Gruppe	12	view_gruppe
49	Can add Feedback / Anregung	13	add_feedback
50	Can change Feedback / Anregung	13	change_feedback
51	Can delete Feedback / Anregung	13	delete_feedback
52	Can view Feedback / Anregung	13	view_feedback
53	Can add Mitarbeitereintrag	14	add_mitarbeitereintrag
54	Can change Mitarbeitereintrag	14	change_mitarbeitereintrag
55	Can delete Mitarbeitereintrag	14	delete_mitarbeitereintrag
56	Can view Mitarbeitereintrag	14	view_mitarbeitereintrag
57	Can add Raumbelegung	15	add_raumbelegung
58	Can change Raumbelegung	15	change_raumbelegung
59	Can delete Raumbelegung	15	delete_raumbelegung
60	Can view Raumbelegung	15	view_raumbelegung
61	Can add Gemeindetermin	16	add_gemeindetermin
62	Can change Gemeindetermin	16	change_gemeindetermin
63	Can delete Gemeindetermin	16	delete_gemeindetermin
64	Can view Gemeindetermin	16	view_gemeindetermin
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$600000$GMh0zskwTVGhkw12OHIkpA$OCl9wXOZMJpdVUDnzmmHZ2FH/YWa8RS3JyhJTA27vC0=	\N	f	walterdrews				f	t	2025-12-08 23:03:13.438064+00
1	pbkdf2_sha256$600000$vzCGaMNFsYyWNaEIKDWGjD$Clg0DL0ZLUQRHVXNm5See1Z35xl+QD5Igs6Bywbi11g=	2025-12-27 13:12:38.258377+00	t	admin	Daniel	Lanz	d.lanz@technik-lanz.de	t	t	2025-12-08 22:45:09+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
ae25175431e730dab209a83b8fb6b1481cdcbe0e	2025-12-26 23:59:36.65368+00	1
d0241649535a7c0c42c93e67d4a49e70a560bb87	2025-12-27 10:10:36.559585+00	2
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-12-08 23:02:58.086148+00	1	admin	2	[{"changed": {"fields": ["First name", "Last name", "Email address"]}}]	4	1
2	2025-12-08 23:03:13.546924+00	2	walterdrews	1	[{"added": {}}]	4	1
3	2025-12-26 20:26:00.508119+00	19	123, 123	3		10	1
4	2025-12-26 20:26:00.509874+00	18	123, 123	3		10	1
5	2025-12-26 20:26:00.510505+00	22	321, 123	3		10	1
6	2025-12-26 20:26:00.511084+00	20	321, 123123	3		10	1
7	2025-12-26 20:26:00.511683+00	21	321123, 321123	3		10	1
8	2025-12-26 20:26:00.512278+00	27	Lanz, 123	3		10	1
9	2025-12-26 20:26:00.512869+00	37	Lanz, Daniel	3		10	1
10	2025-12-26 20:26:00.513445+00	26	Lanz, Daniel	3		10	1
11	2025-12-26 20:26:00.513989+00	17	Lanz, Daniel	3		10	1
12	2025-12-26 20:26:00.514487+00	38	Lanz, Ttest	3		10	1
13	2025-12-26 20:26:00.515007+00	39	Lanz, Tttrst	3		10	1
14	2025-12-26 20:26:00.515584+00	36	Lanz111, Daniel111	3		10	1
15	2025-12-26 20:26:00.516095+00	23	Registration, Test	3		10	1
16	2025-12-26 20:26:00.516601+00	32	Test, Test	3		10	1
17	2025-12-26 20:26:00.517145+00	33	Test, Test1	3		10	1
18	2025-12-26 20:26:00.517794+00	40	Test2, TEST	3		10	1
19	2025-12-26 20:26:00.518326+00	41	Test2, Test	3		10	1
20	2025-12-26 20:26:00.518802+00	14	[ID:14], Gelöscht	3		10	1
21	2025-12-26 20:26:00.519304+00	15	[ID:15], Gelöscht	3		10	1
22	2025-12-26 20:26:00.519812+00	16	[ID:16], Gelöscht	3		10	1
23	2025-12-26 20:26:00.520313+00	2	[ID:2], Gelöscht	3		10	1
24	2025-12-26 20:26:00.520793+00	31	dfyhdyfh, fbhdsfyhdf	3		10	1
25	2025-12-26 20:26:00.521311+00	30	ujashvbfi, hvbdfishb	3		10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	authtoken	token
8	authtoken	tokenproxy
9	members	servicetag
10	members	member
11	members	familie
12	members	gruppe
13	members	feedback
14	kalender	mitarbeitereintrag
15	kalender	raumbelegung
16	kalender	gemeindetermin
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-11-24 22:38:04.141674+00
2	auth	0001_initial	2025-11-24 22:38:04.164742+00
3	admin	0001_initial	2025-11-24 22:38:04.171458+00
4	admin	0002_logentry_remove_auto_add	2025-11-24 22:38:04.174955+00
5	admin	0003_logentry_add_action_flag_choices	2025-11-24 22:38:04.17768+00
6	contenttypes	0002_remove_content_type_name	2025-11-24 22:38:04.183354+00
7	auth	0002_alter_permission_name_max_length	2025-11-24 22:38:04.186425+00
8	auth	0003_alter_user_email_max_length	2025-11-24 22:38:04.189425+00
9	auth	0004_alter_user_username_opts	2025-11-24 22:38:04.192057+00
10	auth	0005_alter_user_last_login_null	2025-11-24 22:38:04.195202+00
11	auth	0006_require_contenttypes_0002	2025-11-24 22:38:04.195897+00
12	auth	0007_alter_validators_add_error_messages	2025-11-24 22:38:04.199133+00
13	auth	0008_alter_user_username_max_length	2025-11-24 22:38:04.203268+00
14	auth	0009_alter_user_last_name_max_length	2025-11-24 22:38:04.206512+00
15	auth	0010_alter_group_name_max_length	2025-11-24 22:38:04.209903+00
16	auth	0011_update_proxy_permissions	2025-11-24 22:38:04.212459+00
17	auth	0012_alter_user_first_name_max_length	2025-11-24 22:38:04.215471+00
22	sessions	0001_initial	2025-11-24 22:38:04.267591+00
23	authtoken	0001_initial	2025-11-28 02:08:24.845655+00
24	authtoken	0002_auto_20160226_1747	2025-11-28 02:08:24.855376+00
25	authtoken	0003_tokenproxy	2025-11-28 02:08:24.85634+00
26	authtoken	0004_alter_tokenproxy_options	2025-11-28 02:08:24.85818+00
27	members	0005_member_address_member_email_member_phone	2025-11-28 02:08:24.867178+00
28	members	0006_member_photo_member_signature	2025-11-28 02:15:19.404971+00
29	members	0007_alter_member_photo_alter_member_signature	2025-11-28 02:17:52.302859+00
30	members	0008_child_remove_member_is_member_remove_member_kinder_and_more	2025-11-28 02:43:16.994188+00
31	members	0009_familie_member_is_member_delete_child_familie_kinder_and_more	2025-11-28 02:54:05.317639+00
32	members	0010_member_privacy_policy_pdf	2025-11-28 03:02:47.613148+00
34	members	0006_alter_familie_options_remove_member_kinder_and_more	2025-11-28 11:43:49.691058+00
38	members	0008_member_photo_thumb	2025-11-28 21:26:56.322482+00
39	members	0008_gruppe_parent_gruppe_member_photo_thumb_and_more	2025-12-01 17:45:35.652479+00
41	members	0010_gruppe_parent_gruppe_member_photo_thumb_and_more	2025-12-04 13:13:56.862215+00
42	members	0010_gruppe_parent_gruppe_member_anonymized_at_and_more	2025-12-04 14:17:02.248214+00
44	members	0012_gruppe_parent_gruppe_member_anonymized_at_and_more	2025-12-05 16:31:13.800043+00
46	members	0002_alter_member_current_service_and_more	2025-12-08 21:07:18.68156+00
47	members	0003_servicetag_remove_member_current_service_and_more	2025-12-08 21:07:18.701847+00
48	members	0004_member_is_member_member_kinder_familie_delete_child	2025-12-08 21:07:18.722492+00
49	members	0005_alter_familie_options_remove_member_kinder_and_more	2025-12-08 21:07:18.741044+00
50	members	0006_alter_familie_options_remove_member_address_and_more	2025-12-08 21:07:18.785393+00
51	members	0007_remove_member_kinder_gruppe	2025-12-08 21:07:18.809785+00
52	members	0009_member_signature_location	2025-12-08 21:07:18.815651+00
53	members	0011_member_is_child_member_is_youth	2025-12-08 21:07:18.823631+00
54	members	0012_familie_family_code_gruppe_parent_gruppe_and_more	2025-12-08 21:08:49.956443+00
55	members	0013_add_family_code	2025-12-08 21:10:33.819252+00
56	members	0014_gruppe_parent_gruppe_member_anonymized_at_and_more	2025-12-08 22:14:15.540495+00
57	members	0001_initial	2025-12-08 22:54:10.646766+00
58	kalender	0001_initial	2025-12-26 20:51:01.104512+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
rkbaxkxg1m10lh6cq4agf24z13tmevo1	.eJxVjMEOwiAQRP-FsyFsK2Xr0bvfQJZlkaqBpLQn47_bJj1o5jbvzbyVp3XJfm0y-ymqiwJ1-u0C8VPKDuKDyr1qrmWZp6B3RR-06VuN8roe7t9Bppa3NbGQOVPXx4Bu7AVMIkyMHaAbwDIT49g5wLgFkwUx0g9iLScOYEl9vvanOGY:1vSkFV:OSZqZudjRnoVabD-7GFMMsIELnz_D5CpkjShgBHplY4	2025-12-22 23:02:33.6322+00
i2od8jgd32q71ntggrbikte4ssajxfva	.eJxVjMEOwiAQRP-FsyFsK2Xr0bvfQJZlkaqBpLQn47_bJj1o5jbvzbyVp3XJfm0y-ymqiwJ1-u0C8VPKDuKDyr1qrmWZp6B3RR-06VuN8roe7t9Bppa3NbGQOVPXx4Bu7AVMIkyMHaAbwDIT49g5wLgFkwUx0g9iLScOYEl9vvanOGY:1vUr4P:lY8nMLbYa7ZJnUbbv8iDxMRQQoncythoSBgA6xd3UMM	2025-12-28 18:43:49.337096+00
0d70moo2tfwcazs510exvi2zdabqrsq1	.eJxVjMEOwiAQRP-FsyFsK2Xr0bvfQJZlkaqBpLQn47_bJj1o5jbvzbyVp3XJfm0y-ymqiwJ1-u0C8VPKDuKDyr1qrmWZp6B3RR-06VuN8roe7t9Bppa3NbGQOVPXx4Bu7AVMIkyMHaAbwDIT49g5wLgFkwUx0g9iLScOYEl9vvanOGY:1vZDyo:DRwGKqJfeLWB0ajEq9yYplJymzvIJ69CKwKSsgt446w	2026-01-09 20:00:06.320804+00
khtme6ta7byldwnlarn7zji6pygibd99	.eJxVjMEOwiAQRP-FsyFsK2Xr0bvfQJZlkaqBpLQn47_bJj1o5jbvzbyVp3XJfm0y-ymqiwJ1-u0C8VPKDuKDyr1qrmWZp6B3RR-06VuN8roe7t9Bppa3NbGQOVPXx4Bu7AVMIkyMHaAbwDIT49g5wLgFkwUx0g9iLScOYEl9vvanOGY:1vZU62:wIh9D1FOvQ3MDgQTB5W-CUEqlcYN-20JNHahJ_iah7I	2026-01-10 13:12:38.259742+00
\.


--
-- Data for Name: kalender_gemeindetermin; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.kalender_gemeindetermin (id, titel, datum, startzeit, endzeit, beschreibung, erstellt_am, aktualisiert_am, erstellt_von_id) FROM stdin;
2	Hochzeit	2026-01-17	10:00:00	20:00:00		2025-12-26 22:39:18.316555+00	2025-12-26 22:39:18.316569+00	2
\.


--
-- Data for Name: kalender_mitarbeitereintrag; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.kalender_mitarbeitereintrag (id, person, datum, startzeit, endzeit, typ, titel, beschreibung, erstellt_am, aktualisiert_am, erstellt_von_id) FROM stdin;
1	123	0123-03-12	12:03:00	12:03:00	urlaub	terst	123	2025-12-26 23:00:02.095655+00	2025-12-26 23:00:02.095675+00	1
\.


--
-- Data for Name: kalender_raumbelegung; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.kalender_raumbelegung (id, raum, titel, datum, startzeit, endzeit, beschreibung, erstellt_am, aktualisiert_am, erstellt_von_id) FROM stdin;
1	123	test	2025-12-11	12:12:00	12:12:00	123	2025-12-26 22:55:15.319208+00	2025-12-26 22:55:15.319221+00	1
\.


--
-- Data for Name: members_familie; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.members_familie (id, name, family_code, mutter_id, vater_id) FROM stdin;
2	Lanz	RBE4	4	1
3	Drews	RZR5	13	6
9	Maisinger	RAMC	\N	24
17	Vorname Nachname	VTK1	\N	43
\.


--
-- Data for Name: members_familie_kinder; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.members_familie_kinder (id, familie_id, member_id) FROM stdin;
3	2	3
4	2	5
5	3	7
6	3	8
7	3	9
8	3	10
9	3	11
10	3	12
12	9	25
17	17	44
18	17	45
\.


--
-- Data for Name: members_feedback; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.members_feedback (id, category, text, created_at, member_id) FROM stdin;
\.


--
-- Data for Name: members_gruppe; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.members_gruppe (id, name, size_type, description, created_at, updated_at, parent_gruppe_id) FROM stdin;
1	Gruppe A	large		2025-12-08 23:12:40.59354+00	2025-12-08 23:12:40.593554+00	\N
2	Gruppe B	large		2025-12-08 23:12:49.419826+00	2025-12-08 23:12:49.419842+00	\N
3	Gruppe C	large		2025-12-08 23:12:58.465586+00	2025-12-08 23:12:58.465601+00	\N
4	Gruppe D	large		2025-12-08 23:13:03.306202+00	2025-12-08 23:13:03.306216+00	\N
5	Gruppe E	large		2025-12-08 23:13:09.787799+00	2025-12-08 23:13:09.787815+00	\N
8	Gruppe A-3	small		2025-12-08 23:13:52.982912+00	2025-12-08 23:13:52.982928+00	1
9	Gruppe A-4	small		2025-12-08 23:14:06.095932+00	2025-12-08 23:14:06.095947+00	1
10	Gruppe A-5	small		2025-12-08 23:14:18.658263+00	2025-12-08 23:14:18.658279+00	1
11	Gruppe B-1	small		2025-12-08 23:14:51.169241+00	2025-12-08 23:14:51.169257+00	2
12	Gruppe B-2	small		2025-12-08 23:15:04.722134+00	2025-12-08 23:15:04.722147+00	2
13	Gruppe B-3	small		2025-12-08 23:15:12.58702+00	2025-12-08 23:15:12.587034+00	2
14	Gruppe B-4	small		2025-12-08 23:15:26.859378+00	2025-12-08 23:15:26.859394+00	2
15	Gruppe B-5	small		2025-12-08 23:15:41.843748+00	2025-12-08 23:15:41.843763+00	2
16	Gruppe C-1	small		2025-12-08 23:16:03.816993+00	2025-12-08 23:16:03.817008+00	3
17	Gruppe C-2	small		2025-12-08 23:16:13.267461+00	2025-12-08 23:16:13.267476+00	3
18	Gruppe C-3	small		2025-12-08 23:16:21.445618+00	2025-12-08 23:16:21.445644+00	3
19	Gruppe C-4	small		2025-12-08 23:16:33.741011+00	2025-12-08 23:16:33.741024+00	3
20	Gruppe C-5	small		2025-12-08 23:16:45.687578+00	2025-12-08 23:16:45.687595+00	3
21	Gruppe D-1	small		2025-12-08 23:17:07.147863+00	2025-12-08 23:17:07.147877+00	4
22	Gruppe D-2	small		2025-12-08 23:17:17.156679+00	2025-12-08 23:17:17.156692+00	4
23	Gruppe D-3	small		2025-12-08 23:17:28.413142+00	2025-12-08 23:17:28.413158+00	4
24	Gruppe D-4	small		2025-12-08 23:17:37.735929+00	2025-12-08 23:17:37.735945+00	4
25	Gruppe D-5	small		2025-12-08 23:17:48.014603+00	2025-12-08 23:17:48.014621+00	4
26	Gruppe E-1	small		2025-12-08 23:18:05.808148+00	2025-12-08 23:18:05.808167+00	5
27	Gruppe E-2	small		2025-12-08 23:18:15.975165+00	2025-12-08 23:18:15.97518+00	5
28	Gruppe E-3	small		2025-12-08 23:18:26.465729+00	2025-12-08 23:18:26.465743+00	5
29	Gruppe E-4	small		2025-12-08 23:18:35.457006+00	2025-12-08 23:18:35.457019+00	5
30	Gruppe E-5	small		2025-12-08 23:18:45.823168+00	2025-12-08 23:18:45.823182+00	5
31	Gruppe A-6	small		2025-12-09 05:49:42.357271+00	2025-12-09 05:49:42.357287+00	1
32	Gruppe B-6	small		2025-12-09 05:50:13.037317+00	2025-12-09 05:50:13.03733+00	2
33	Gruppe C-6	small		2025-12-09 05:50:45.64503+00	2025-12-09 05:50:45.645046+00	3
34	Gruppe E-6	small		2025-12-09 05:51:18.007419+00	2025-12-09 05:51:18.007432+00	5
6	Gruppe A-1	small		2025-12-08 23:13:23.82064+00	2025-12-14 09:41:18.577247+00	1
7	Gruppe A-2	small		2025-12-08 23:13:34.505145+00	2025-12-14 09:41:35.911196+00	1
\.


--
-- Data for Name: members_gruppe_ansprechpartner; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.members_gruppe_ansprechpartner (id, gruppe_id, member_id) FROM stdin;
1	6	6
2	7	6
\.


--
-- Data for Name: members_gruppe_members; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.members_gruppe_members (id, gruppe_id, member_id) FROM stdin;
5	1	1
7	6	1
12	1	6
14	7	6
15	1	24
16	7	24
17	2	13
18	14	13
19	1	28
20	9	28
21	2	4
22	32	4
\.


--
-- Data for Name: members_member; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.members_member (id, last_name, first_name, email, phone, street, postal_code, city, date_of_birth, married_since, profession, nationality, status, is_donor, is_member, is_youth, is_child, community_suggestions, photo, photo_thumb, signature, signature_location, privacy_policy_pdf, privacy_membership, privacy_whatsapp, privacy_data_protection, privacy_data_release, privacy_donation, privacy_children, deleted_at, anonymized_at, archived_at, archival_reason, deletion_certificate_url, deleted_by_id, marriage_location) FROM stdin;
1	Lanz	Daniel	lanz.d1998@gmail.com	01742638614	Vogelbeerweg 5	77656	Offenburg	1998-03-17	2022-06-11	IT	Deutsch	active	t	t	f	f		members/photos/member_1_photo_57AyB5M.jpg	members/photos/thumbs/member_1_thumb_ppc4QN7.jpg	members/signatures/signature_OYueZhb.png	Offenburg	members/privacy/datenschutz_Lanz_Daniel_sDGeyMA.pdf	t	t	t	t	t	t	\N	\N	\N			\N	Lahr
6	Drews	Walter	walterdrews@gmx.de	017620219780	Im Grund 4	77963	Schwanau/ Wittenweier	1990-12-26	2013-09-27	Servicetechniker	Deutsch	active	t	t	f	f	Bessere Betreuung der Mitglieder			members/signatures/signature_HhRGxVf.png	Wittenweier	members/privacy/datenschutz_Drews_Walter_uMDV8QX.pdf	t	t	t	t	t	t	\N	\N	\N			\N	
24	Maisinger	Daniel	dmaisinger@googlemail.com	01727499340	Eichholzstr 4	77933	Lahr	1981-04-22	\N	Lagerist	Deutsch	active	t	t	f	f				members/signatures/signature_fFcSASK.png	Lahr	members/privacy/datenschutz_Maisinger_Daniel.pdf	t	t	t	t	t	t	\N	\N	\N			\N	
8	Drews	Emil		017620219780	Im Grund 4	77963	Schwanau/ Wittenweier	2017-08-23	\N			minor	f	f	f	t					Lahr		f	f	f	f	f	f	\N	\N	\N			\N	
12	Drews	Dave		017620219780	Im Grund 4	77963	Schwanau/ Wittenweier	2025-01-21	\N			minor	f	f	f	t					Lahr		f	f	f	f	f	f	\N	\N	\N			\N	
11	Drews	Dayana		017620219780	Im Grund 4	77963	Schwanau/ Wittenweier	2023-05-26	\N			minor	f	f	f	t					Lahr		f	f	f	f	f	f	\N	\N	\N			\N	
9	Drews	Milan		017620219780	Im Grund 4	77963	Schwanau/ Wittenweier	2020-07-06	\N		Deutsch	minor	f	f	f	t					Lahr		f	f	f	f	f	f	\N	\N	\N			\N	
7	Drews	Leon		017620219780	Im Grund 4	77963	Schwanau/ Wittenweier	2016-05-28	\N			minor	f	f	f	t					Lahr		f	f	f	f	f	f	\N	\N	\N			\N	
10	Drews	Dorothea		017620219780	Im Grund 4	77963	Schwanau/ Wittenweier	2022-01-26	\N			minor	f	f	f	t					Lahr		f	f	f	f	f	f	\N	\N	\N			\N	
13	Drews	Lilli	lilli-kronhard@t-online.de	017680875342	Im Grund 4	77963	Schwanau/ Wittenweier	1990-12-01	2013-09-27		Deutsch	active	t	t	f	f				members/signatures/signature_VoT78TN.png	Wittenweier	members/privacy/datenschutz_Drews_Lilli.pdf	t	t	t	t	t	t	\N	\N	\N			\N	\N
5	Lanz	Jasmin		01742638614	Vogelbeerweg 5	77656	Offenburg	2025-11-15	\N			guest	f	f	f	t					Lahr		f	f	f	f	f	f	\N	\N	\N			\N	\N
3	Lanz	Nikita	\N		Vogelbeerweg 5	77656	Offenburg	2023-04-23	\N			guest	f	f	f	t					Lahr		f	f	f	f	f	f	\N	\N	\N			\N	\N
25	Maisinger	Gloria	\N		Eichholzstr 4	77933	Lahr	2017-03-10	\N			guest	f	f	f	t					Lahr	members/privacy/datenschutz_Maisinger_Gloria.pdf	t	t	t	t	t	t	\N	\N	\N			\N	\N
4	Lanz	Julia	lanzz.d1998@gmail.com	01742638614	Vogelbeerweg 5	77656	Offenburg	1995-03-06	2022-06-11	Koch	Deutsch	active	t	t	f	f				members/signatures/signature_wasWMDV.png	Lahr	members/privacy/datenschutz_Lanz_Julia_jqzooUo.pdf	t	t	t	t	t	t	\N	\N	\N			\N	\N
43	Nachname	Vorname	e@mail.de	0123456789	Straße 5	1234567	Offenburg	1980-01-01	1980-01-01	Beruf	Deutsch	guest	f	f	f	f				members/signatures/signature.png	Lahr	members/privacy/datenschutz_Nachname_Vorname.pdf	t	t	t	t	t	t	\N	\N	\N			\N	
29	Drews	Dave	\N		Im Grund 4, 77963 Schwanau	77963	Schwanau/ Wittenweier	2025-01-27	\N			guest	f	f	f	t					Lahr	members/privacy/datenschutz_Drews_Dave.pdf	t	t	t	t	t	t	\N	\N	\N			\N	
44	Nachname	Kind1Vorname	\N		Straße 5	1234567	Offenburg	2000-01-01	\N			guest	f	f	f	t					Lahr	members/privacy/datenschutz_Nachname_Kind1Vorname.pdf	t	t	t	t	t	t	\N	\N	\N			\N	
28	Drews	Walter		017620219780	Im Grund 4, 77963 Schwanau	77963	Schwanau/ Wittenweier	\N	\N		Deutsch	active	f	t	f	f				members/signatures/signature_oHbIqrr.png	Wittenweier	members/privacy/datenschutz_Drews_Walter_txpNs0I.pdf	t	t	t	t	t	t	2025-12-14 19:40:16.732752+00	\N	\N			2	
45	Nachname	Kind2Vorname	\N		Straße 5	1234567	Offenburg	2020-01-01	\N			guest	f	f	f	t					Lahr	members/privacy/datenschutz_Nachname_Kind2Vorname.pdf	t	t	t	t	t	t	\N	\N	\N			\N	
\.


--
-- Data for Name: members_member_current_services; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.members_member_current_services (id, member_id, servicetag_id) FROM stdin;
1	1	1
2	1	2
3	1	3
4	1	4
5	4	4
6	6	5
7	6	6
\.


--
-- Data for Name: members_member_desired_services; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.members_member_desired_services (id, member_id, servicetag_id) FROM stdin;
\.


--
-- Data for Name: members_servicetag; Type: TABLE DATA; Schema: public; Owner: FECGLahrMitglieder_user
--

COPY public.members_servicetag (id, name, slug) FROM stdin;
1	Beamer	beamer
2	Rehadienst	rehadienst
3	Fußwaschung	fuwaschung
4	Sonntagsküche	sonntagskuche
5	Büro	buro
6	Gebäudetechnik	gebaudetechnik
7	Gebetsgruppe	gebetsgruppe
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 25, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 58, true);


--
-- Name: kalender_gemeindetermin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.kalender_gemeindetermin_id_seq', 3, true);


--
-- Name: kalender_mitarbeitereintrag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.kalender_mitarbeitereintrag_id_seq', 1, true);


--
-- Name: kalender_raumbelegung_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.kalender_raumbelegung_id_seq', 1, true);


--
-- Name: members_familie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.members_familie_id_seq', 17, true);


--
-- Name: members_familie_kinder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.members_familie_kinder_id_seq', 18, true);


--
-- Name: members_feedback_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.members_feedback_id_seq', 1, false);


--
-- Name: members_gruppe_ansprechpartner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.members_gruppe_ansprechpartner_id_seq', 2, true);


--
-- Name: members_gruppe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.members_gruppe_id_seq', 34, true);


--
-- Name: members_gruppe_members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.members_gruppe_members_id_seq', 22, true);


--
-- Name: members_member_current_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.members_member_current_services_id_seq', 9, true);


--
-- Name: members_member_desired_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.members_member_desired_services_id_seq', 1, false);


--
-- Name: members_member_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.members_member_id_seq', 45, true);


--
-- Name: members_servicetag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: FECGLahrMitglieder_user
--

SELECT pg_catalog.setval('public.members_servicetag_id_seq', 7, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: kalender_gemeindetermin kalender_gemeindetermin_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.kalender_gemeindetermin
    ADD CONSTRAINT kalender_gemeindetermin_pkey PRIMARY KEY (id);


--
-- Name: kalender_mitarbeitereintrag kalender_mitarbeitereintrag_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.kalender_mitarbeitereintrag
    ADD CONSTRAINT kalender_mitarbeitereintrag_pkey PRIMARY KEY (id);


--
-- Name: kalender_raumbelegung kalender_raumbelegung_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.kalender_raumbelegung
    ADD CONSTRAINT kalender_raumbelegung_pkey PRIMARY KEY (id);


--
-- Name: members_familie members_familie_family_code_key; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_familie
    ADD CONSTRAINT members_familie_family_code_key UNIQUE (family_code);


--
-- Name: members_familie_kinder members_familie_kinder_familie_id_member_id_29acb703_uniq; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_familie_kinder
    ADD CONSTRAINT members_familie_kinder_familie_id_member_id_29acb703_uniq UNIQUE (familie_id, member_id);


--
-- Name: members_familie_kinder members_familie_kinder_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_familie_kinder
    ADD CONSTRAINT members_familie_kinder_pkey PRIMARY KEY (id);


--
-- Name: members_familie members_familie_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_familie
    ADD CONSTRAINT members_familie_pkey PRIMARY KEY (id);


--
-- Name: members_feedback members_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_feedback
    ADD CONSTRAINT members_feedback_pkey PRIMARY KEY (id);


--
-- Name: members_gruppe_ansprechpartner members_gruppe_ansprechp_gruppe_id_member_id_9643d945_uniq; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_gruppe_ansprechpartner
    ADD CONSTRAINT members_gruppe_ansprechp_gruppe_id_member_id_9643d945_uniq UNIQUE (gruppe_id, member_id);


--
-- Name: members_gruppe_ansprechpartner members_gruppe_ansprechpartner_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_gruppe_ansprechpartner
    ADD CONSTRAINT members_gruppe_ansprechpartner_pkey PRIMARY KEY (id);


--
-- Name: members_gruppe_members members_gruppe_members_gruppe_id_member_id_8134b6b3_uniq; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_gruppe_members
    ADD CONSTRAINT members_gruppe_members_gruppe_id_member_id_8134b6b3_uniq UNIQUE (gruppe_id, member_id);


--
-- Name: members_gruppe_members members_gruppe_members_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_gruppe_members
    ADD CONSTRAINT members_gruppe_members_pkey PRIMARY KEY (id);


--
-- Name: members_gruppe members_gruppe_name_key; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_gruppe
    ADD CONSTRAINT members_gruppe_name_key UNIQUE (name);


--
-- Name: members_gruppe members_gruppe_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_gruppe
    ADD CONSTRAINT members_gruppe_pkey PRIMARY KEY (id);


--
-- Name: members_member_current_services members_member_current_s_member_id_servicetag_id_db4986b8_uniq; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_member_current_services
    ADD CONSTRAINT members_member_current_s_member_id_servicetag_id_db4986b8_uniq UNIQUE (member_id, servicetag_id);


--
-- Name: members_member_current_services members_member_current_services_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_member_current_services
    ADD CONSTRAINT members_member_current_services_pkey PRIMARY KEY (id);


--
-- Name: members_member_desired_services members_member_desired_s_member_id_servicetag_id_3667492a_uniq; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_member_desired_services
    ADD CONSTRAINT members_member_desired_s_member_id_servicetag_id_3667492a_uniq UNIQUE (member_id, servicetag_id);


--
-- Name: members_member_desired_services members_member_desired_services_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_member_desired_services
    ADD CONSTRAINT members_member_desired_services_pkey PRIMARY KEY (id);


--
-- Name: members_member members_member_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_member
    ADD CONSTRAINT members_member_pkey PRIMARY KEY (id);


--
-- Name: members_servicetag members_servicetag_name_key; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_servicetag
    ADD CONSTRAINT members_servicetag_name_key UNIQUE (name);


--
-- Name: members_servicetag members_servicetag_pkey; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_servicetag
    ADD CONSTRAINT members_servicetag_pkey PRIMARY KEY (id);


--
-- Name: members_servicetag members_servicetag_slug_key; Type: CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_servicetag
    ADD CONSTRAINT members_servicetag_slug_key UNIQUE (slug);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: kalender_gemeindetermin_erstellt_von_id_b59cb950; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX kalender_gemeindetermin_erstellt_von_id_b59cb950 ON public.kalender_gemeindetermin USING btree (erstellt_von_id);


--
-- Name: kalender_mitarbeitereintrag_erstellt_von_id_490c71d8; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX kalender_mitarbeitereintrag_erstellt_von_id_490c71d8 ON public.kalender_mitarbeitereintrag USING btree (erstellt_von_id);


--
-- Name: kalender_raumbelegung_erstellt_von_id_e9b816b3; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX kalender_raumbelegung_erstellt_von_id_e9b816b3 ON public.kalender_raumbelegung USING btree (erstellt_von_id);


--
-- Name: members_familie_family_code_161463a1_like; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_familie_family_code_161463a1_like ON public.members_familie USING btree (family_code varchar_pattern_ops);


--
-- Name: members_familie_kinder_familie_id_f0aae52c; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_familie_kinder_familie_id_f0aae52c ON public.members_familie_kinder USING btree (familie_id);


--
-- Name: members_familie_kinder_member_id_b2196478; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_familie_kinder_member_id_b2196478 ON public.members_familie_kinder USING btree (member_id);


--
-- Name: members_familie_mutter_id_ad621921; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_familie_mutter_id_ad621921 ON public.members_familie USING btree (mutter_id);


--
-- Name: members_familie_vater_id_4efd53d1; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_familie_vater_id_4efd53d1 ON public.members_familie USING btree (vater_id);


--
-- Name: members_feedback_member_id_0fdfd014; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_feedback_member_id_0fdfd014 ON public.members_feedback USING btree (member_id);


--
-- Name: members_gruppe_ansprechpartner_gruppe_id_5e0ac48e; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_gruppe_ansprechpartner_gruppe_id_5e0ac48e ON public.members_gruppe_ansprechpartner USING btree (gruppe_id);


--
-- Name: members_gruppe_ansprechpartner_member_id_90c05518; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_gruppe_ansprechpartner_member_id_90c05518 ON public.members_gruppe_ansprechpartner USING btree (member_id);


--
-- Name: members_gruppe_members_gruppe_id_efcda193; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_gruppe_members_gruppe_id_efcda193 ON public.members_gruppe_members USING btree (gruppe_id);


--
-- Name: members_gruppe_members_member_id_0de056de; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_gruppe_members_member_id_0de056de ON public.members_gruppe_members USING btree (member_id);


--
-- Name: members_gruppe_name_bf31c935_like; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_gruppe_name_bf31c935_like ON public.members_gruppe USING btree (name varchar_pattern_ops);


--
-- Name: members_gruppe_parent_gruppe_id_02e09370; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_gruppe_parent_gruppe_id_02e09370 ON public.members_gruppe USING btree (parent_gruppe_id);


--
-- Name: members_member_current_services_member_id_3d7fc856; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_member_current_services_member_id_3d7fc856 ON public.members_member_current_services USING btree (member_id);


--
-- Name: members_member_current_services_servicetag_id_80235e4c; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_member_current_services_servicetag_id_80235e4c ON public.members_member_current_services USING btree (servicetag_id);


--
-- Name: members_member_deleted_by_id_2c17ab1f; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_member_deleted_by_id_2c17ab1f ON public.members_member USING btree (deleted_by_id);


--
-- Name: members_member_desired_services_member_id_682015e5; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_member_desired_services_member_id_682015e5 ON public.members_member_desired_services USING btree (member_id);


--
-- Name: members_member_desired_services_servicetag_id_ffb9d1f0; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_member_desired_services_servicetag_id_ffb9d1f0 ON public.members_member_desired_services USING btree (servicetag_id);


--
-- Name: members_servicetag_name_bde12360_like; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_servicetag_name_bde12360_like ON public.members_servicetag USING btree (name varchar_pattern_ops);


--
-- Name: members_servicetag_slug_8252b085_like; Type: INDEX; Schema: public; Owner: FECGLahrMitglieder_user
--

CREATE INDEX members_servicetag_slug_8252b085_like ON public.members_servicetag USING btree (slug varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kalender_gemeindetermin kalender_gemeindeter_erstellt_von_id_b59cb950_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.kalender_gemeindetermin
    ADD CONSTRAINT kalender_gemeindeter_erstellt_von_id_b59cb950_fk_auth_user FOREIGN KEY (erstellt_von_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kalender_mitarbeitereintrag kalender_mitarbeiter_erstellt_von_id_490c71d8_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.kalender_mitarbeitereintrag
    ADD CONSTRAINT kalender_mitarbeiter_erstellt_von_id_490c71d8_fk_auth_user FOREIGN KEY (erstellt_von_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kalender_raumbelegung kalender_raumbelegung_erstellt_von_id_e9b816b3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.kalender_raumbelegung
    ADD CONSTRAINT kalender_raumbelegung_erstellt_von_id_e9b816b3_fk_auth_user_id FOREIGN KEY (erstellt_von_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_familie_kinder members_familie_kind_familie_id_f0aae52c_fk_members_f; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_familie_kinder
    ADD CONSTRAINT members_familie_kind_familie_id_f0aae52c_fk_members_f FOREIGN KEY (familie_id) REFERENCES public.members_familie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_familie_kinder members_familie_kinder_member_id_b2196478_fk_members_member_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_familie_kinder
    ADD CONSTRAINT members_familie_kinder_member_id_b2196478_fk_members_member_id FOREIGN KEY (member_id) REFERENCES public.members_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_familie members_familie_mutter_id_ad621921_fk_members_member_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_familie
    ADD CONSTRAINT members_familie_mutter_id_ad621921_fk_members_member_id FOREIGN KEY (mutter_id) REFERENCES public.members_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_familie members_familie_vater_id_4efd53d1_fk_members_member_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_familie
    ADD CONSTRAINT members_familie_vater_id_4efd53d1_fk_members_member_id FOREIGN KEY (vater_id) REFERENCES public.members_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_feedback members_feedback_member_id_0fdfd014_fk_members_member_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_feedback
    ADD CONSTRAINT members_feedback_member_id_0fdfd014_fk_members_member_id FOREIGN KEY (member_id) REFERENCES public.members_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_gruppe_ansprechpartner members_gruppe_anspr_gruppe_id_5e0ac48e_fk_members_g; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_gruppe_ansprechpartner
    ADD CONSTRAINT members_gruppe_anspr_gruppe_id_5e0ac48e_fk_members_g FOREIGN KEY (gruppe_id) REFERENCES public.members_gruppe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_gruppe_ansprechpartner members_gruppe_anspr_member_id_90c05518_fk_members_m; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_gruppe_ansprechpartner
    ADD CONSTRAINT members_gruppe_anspr_member_id_90c05518_fk_members_m FOREIGN KEY (member_id) REFERENCES public.members_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_gruppe_members members_gruppe_members_gruppe_id_efcda193_fk_members_gruppe_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_gruppe_members
    ADD CONSTRAINT members_gruppe_members_gruppe_id_efcda193_fk_members_gruppe_id FOREIGN KEY (gruppe_id) REFERENCES public.members_gruppe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_gruppe_members members_gruppe_members_member_id_0de056de_fk_members_member_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_gruppe_members
    ADD CONSTRAINT members_gruppe_members_member_id_0de056de_fk_members_member_id FOREIGN KEY (member_id) REFERENCES public.members_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_gruppe members_gruppe_parent_gruppe_id_02e09370_fk_members_gruppe_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_gruppe
    ADD CONSTRAINT members_gruppe_parent_gruppe_id_02e09370_fk_members_gruppe_id FOREIGN KEY (parent_gruppe_id) REFERENCES public.members_gruppe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_member_current_services members_member_curre_member_id_3d7fc856_fk_members_m; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_member_current_services
    ADD CONSTRAINT members_member_curre_member_id_3d7fc856_fk_members_m FOREIGN KEY (member_id) REFERENCES public.members_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_member_current_services members_member_curre_servicetag_id_80235e4c_fk_members_s; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_member_current_services
    ADD CONSTRAINT members_member_curre_servicetag_id_80235e4c_fk_members_s FOREIGN KEY (servicetag_id) REFERENCES public.members_servicetag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_member members_member_deleted_by_id_2c17ab1f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_member
    ADD CONSTRAINT members_member_deleted_by_id_2c17ab1f_fk_auth_user_id FOREIGN KEY (deleted_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_member_desired_services members_member_desir_member_id_682015e5_fk_members_m; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_member_desired_services
    ADD CONSTRAINT members_member_desir_member_id_682015e5_fk_members_m FOREIGN KEY (member_id) REFERENCES public.members_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: members_member_desired_services members_member_desir_servicetag_id_ffb9d1f0_fk_members_s; Type: FK CONSTRAINT; Schema: public; Owner: FECGLahrMitglieder_user
--

ALTER TABLE ONLY public.members_member_desired_services
    ADD CONSTRAINT members_member_desir_servicetag_id_ffb9d1f0_fk_members_s FOREIGN KEY (servicetag_id) REFERENCES public.members_servicetag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 2SBFzRdgNdXLMOeS3Dh1PHPQoRDODZxBtHPTgoG4nfpBJU1KsCV80xHiErrREbd

