# Generated by Django 4.2.27 on 2025-12-28 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Dienst-Name')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Dienst (Tag)',
                'verbose_name_plural': 'Dienste (Tags)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familienname')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name (Vorname)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefonnummer')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('married_since', models.DateField(blank=True, null=True, verbose_name='Verheiratet seit')),
                ('marriage_location', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Heiratsort')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Beruf')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationalität')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('passive', 'Passiv'), ('minor', 'Minderjährig'), ('guest', 'Gast')], default='active', max_length=20, verbose_name='Status')),
                ('is_donor', models.BooleanField(default=False, verbose_name='Spender (Ja/Nein)')),
                ('is_member', models.BooleanField(default=True, help_text='Ist diese Person ein offizielles Gemeindemitglied?', verbose_name='Mitglied (Ja/Nein)')),
                ('is_youth', models.BooleanField(default=False, verbose_name='Jugendmitglied (Ja/Nein)')),
                ('is_child', models.BooleanField(default=False, verbose_name='Kind (Ja/Nein)')),
                ('community_suggestions', models.TextField(blank=True, verbose_name='Anregungen der Gemeinde')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Foto')),
                ('photo_thumb', models.ImageField(blank=True, null=True, upload_to='members/photos/thumbs/', verbose_name='Foto (Thumbnail 240x240)')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='members/signatures/', verbose_name='Unterschrift')),
                ('signature_location', models.CharField(blank=True, default='Lahr', max_length=100, verbose_name='Unterschriftsort')),
                ('privacy_policy_pdf', models.FileField(blank=True, help_text='Automatisch generiertes PDF mit Unterschrift', null=True, upload_to='members/privacy/', verbose_name='Datenschutzerklärung (PDF)')),
                ('privacy_membership', models.BooleanField(default=False, verbose_name='DS: Mitgliedschaft')),
                ('privacy_whatsapp', models.BooleanField(default=False, verbose_name='DS: WhatsApp-Gruppe')),
                ('privacy_data_protection', models.BooleanField(default=False, verbose_name='DS: Datenschutzerklärung gelesen')),
                ('privacy_data_release', models.BooleanField(default=False, verbose_name='DS: Datenweitergabe')),
                ('privacy_donation', models.BooleanField(default=False, verbose_name='DS: Spendenquittung')),
                ('privacy_children', models.BooleanField(default=False, verbose_name='DS: Kinder-Daten')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Zeitpunkt des Löschens (Soft-Delete)', null=True, verbose_name='Gelöscht am')),
                ('anonymized_at', models.DateTimeField(blank=True, help_text='Zeitpunkt der Anonymisierung nach 30 Tagen', null=True, verbose_name='Anonymisiert am')),
                ('archived_at', models.DateTimeField(blank=True, help_text='Zeitpunkt der Archivierung (nach 6 Jahren)', null=True, verbose_name='Archiviert am')),
                ('archival_reason', models.CharField(blank=True, help_text='Grund für die Archivierung', max_length=500, verbose_name='Archivierungsgrund')),
                ('deletion_certificate_url', models.FileField(blank=True, help_text='Bestätigung der Datenlöschung', null=True, upload_to='members/deletion_certs/', verbose_name='Löschbestätigung (PDF)')),
                ('current_services', models.ManyToManyField(blank=True, related_name='members_current', to='members.servicetag', verbose_name='Aktuelle Dienste')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Admin der das Mitglied gelöscht hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_members', to=settings.AUTH_USER_MODEL, verbose_name='Gelöscht von')),
                ('desired_services', models.ManyToManyField(blank=True, related_name='members_desired', to='members.servicetag', verbose_name='Wunschdienste')),
            ],
            options={
                'verbose_name': 'Mitglied',
                'verbose_name_plural': 'Mitglieder',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Gruppenname')),
                ('size_type', models.CharField(choices=[('large', 'Große Gruppe (ca. 100 Mitglieder)'), ('small', 'Kleine Gruppe (ca. 30 Mitglieder)')], default='small', max_length=10, verbose_name='Gruppengröße')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('ansprechpartner', models.ManyToManyField(blank=True, help_text='Zuständige Ansprechpartner für diese Gruppe (mehrere möglich)', related_name='gruppen_als_ansprechpartner', to='members.member', verbose_name='Ansprechpartner')),
                ('members', models.ManyToManyField(blank=True, related_name='gruppen', to='members.member', verbose_name='Mitglieder')),
                ('parent_gruppe', models.ForeignKey(blank=True, help_text='Für kleine Gruppen: Zugehörigkeit zu einer großen Gruppe (z.B. Gruppe 1-1 gehört zu Gruppe 1)', limit_choices_to={'size_type': 'large'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='untergruppen', to='members.gruppe', verbose_name='Übergeordnete Gruppe')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('community', 'Wünsche von der Gemeinde'), ('groups', 'Wünsche von den Gruppen'), ('servants', 'Anregungen an die Diener'), ('elders', 'Anregungen an die Ältesten'), ('pastor', 'Anregungen an den Pastor')], max_length=50, verbose_name='Kategorie')),
                ('text', models.TextField(verbose_name='Inhalt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='members.member', verbose_name='Mitglied')),
            ],
            options={
                'verbose_name': 'Feedback / Anregung',
                'verbose_name_plural': 'Feedbacks / Anregungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Familie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Max Müller', max_length=100, verbose_name='Familienname')),
                ('family_code', models.CharField(blank=True, help_text='Eindeutiger Code zum Beitreten der Familie', max_length=20, null=True, unique=True, verbose_name='Familien-Code')),
                ('kinder', models.ManyToManyField(blank=True, related_name='familien_als_kind', to='members.member', verbose_name='Kinder')),
                ('mutter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familien_als_mutter', to='members.member', verbose_name='Mutter')),
                ('vater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familien_als_vater', to='members.member', verbose_name='Vater')),
            ],
            options={
                'verbose_name': 'Familie',
                'verbose_name_plural': 'Familien',
            },
        ),
    ]
