# Generated by Django 4.2.27 on 2025-12-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitarbeitereintrag',
            options={'ordering': ['-datum', 'startzeit'], 'verbose_name': 'Mitarbeitereintrag', 'verbose_name_plural': 'Mitarbeitereintr??ge'},
        ),
        migrations.AddField(
            model_name='gemeindetermin',
            name='farbe',
            field=models.CharField(default='#ea580c', help_text='Hex-Farbcode (z.B. #ea580c)', max_length=7),
        ),
        migrations.AddField(
            model_name='gemeindetermin',
            name='kategorie',
            field=models.CharField(choices=[('intern', 'Intern'), ('extern', 'Extern'), ('allgemein', 'Allgemein'), ('feiertag', 'Feiertag')], default='allgemein', max_length=20),
        ),
        migrations.AddField(
            model_name='mitarbeitereintrag',
            name='farbe',
            field=models.CharField(default='#ea580c', help_text='Hex-Farbcode (z.B. #ea580c)', max_length=7),
        ),
        migrations.AddField(
            model_name='mitarbeitereintrag',
            name='kategorie',
            field=models.CharField(choices=[('intern', 'Intern'), ('extern', 'Extern'), ('allgemein', 'Allgemein')], default='allgemein', max_length=20),
        ),
        migrations.AddField(
            model_name='raumbelegung',
            name='farbe',
            field=models.CharField(default='#ea580c', help_text='Hex-Farbcode (z.B. #ea580c)', max_length=7),
        ),
        migrations.AddField(
            model_name='raumbelegung',
            name='kategorie',
            field=models.CharField(choices=[('intern', 'Intern'), ('extern', 'Extern'), ('allgemein', 'Allgemein')], default='allgemein', max_length=20),
        ),
    ]
